---
:authors:
- !ruby/object:Author
  name: Leora Schmeler
  biography: ''
- &7 !ruby/object:Author
  name: Maybell Klein
  biography: ''
- &6 !ruby/object:Author
  name: Kathe Kuvalis
  biography: ''
- !ruby/object:Author
  name: Gladis Simonis
  biography: ''
- &3 !ruby/object:Author
  name: Zada Jaskolski
  biography: ''
- &8 !ruby/object:Author
  name: Star Bruen
  biography: ''
- &1 !ruby/object:Author
  name: Shaina Donnelly
  biography: ''
- &5 !ruby/object:Author
  name: Maya Cormier
  biography: ''
- &4 !ruby/object:Author
  name: Edmundo Kulas
  biography: ''
- &2 !ruby/object:Author
  name: Louella Rodriguez
  biography: ''
:books:
- &17 !ruby/object:Book
  title: The Blue Wolves
  author: *1
- &9 !ruby/object:Book
  title: Champagne Women
  author: *2
- !ruby/object:Book
  title: Season of the Killer Demon
  author: *1
- &15 !ruby/object:Book
  title: Champagne Ninjas
  author: *3
- &21 !ruby/object:Book
  title: Journey of the Ultra Thief
  author: *4
- !ruby/object:Book
  title: Rise of the Ultra Pickpocket
  author: *5
- &13 !ruby/object:Book
  title: Flying Demon
  author: *6
- &22 !ruby/object:Book
  title: Case of the Missing Danger Demon
  author: *7
- &19 !ruby/object:Book
  title: Case of the Missing Danger Gypsy
  author: *4
- &11 !ruby/object:Book
  title: Legend of Dangerous Monster
  author: *2
- !ruby/object:Book
  title: Fake Brain
  author: *2
- !ruby/object:Book
  title: Green Pickpocket
  author: *8
- !ruby/object:Book
  title: Killer Woman
  author: *2
- !ruby/object:Book
  title: Curse of the Danger Ninja
  author: *4
- !ruby/object:Book
  title: Invasion of the Forbidden Gypsy
  author: *2
:readers:
- &16 !ruby/object:Reader
  name: Hershel Stroman
  email: erick.rutherford@schmidt.ca
  city: Суми
  street: вул. Зелена
  house: 138
- &18 !ruby/object:Reader
  name: Ardis Cassin
  email: oma.stamm@dickens.biz
  city: Конотоп
  street: вул. Рудного
  house: 27
- &12 !ruby/object:Reader
  name: Aurelio Jacobson
  email: aisha.keebler@prosacco.us
  city: Мелітополь
  street: вул. Рудного
  house: 214
- &10 !ruby/object:Reader
  name: Pamula Strosin
  email: margo_heathcote@gorczany.biz
  city: Макіївка
  street: вул. Молодіжна
  house: 127
- !ruby/object:Reader
  name: Gerald Schroeder
  email: wonda.kuhlman@koepp.biz
  city: Олександрія
  street: вул. Винників
  house: 239
- &20 !ruby/object:Reader
  name: Vasiliki Beer
  email: davida_maggio@krajcikcollier.name
  city: Бровари
  street: вул. Коліївщини
  house: 27
- !ruby/object:Reader
  name: Jarrod Monahan
  email: merilyn.thiel@johns.ca
  city: Миколаїв
  street: вул. Староміська
  house: 31
- !ruby/object:Reader
  name: Tyra Donnelly
  email: alessandra_nicolas@rodriguez.ca
  city: Київ
  street: вул. Зелена
  house: 137
- !ruby/object:Reader
  name: Katherina Hermiston
  email: guadalupe@hane.name
  city: Лисичанськ
  street: вул. Рудного
  house: 144
- !ruby/object:Reader
  name: Kia Nicolas
  email: tiffanie.murazik@thompsonschmitt.us
  city: Конотоп
  street: вул. Молодіжна
  house: 132
- &23 !ruby/object:Reader
  name: Frank Doyle
  email: gwen.carroll@cartwright.biz
  city: Нікополь
  street: вул. Зелена
  house: 40
- &14 !ruby/object:Reader
  name: Mao Hane
  email: dotty@kesslerparker.co.uk
  city: Умань
  street: вул. Стрийська
  house: 38
:orders:
- !ruby/object:Order
  book: *9
  reader: *10
  date: 2019-06-03
- !ruby/object:Order
  book: *11
  reader: *12
  date: 2019-06-03
- !ruby/object:Order
  book: *13
  reader: *14
  date: 2019-06-03
- !ruby/object:Order
  book: *11
  reader: *10
  date: 2019-06-03
- !ruby/object:Order
  book: *15
  reader: *16
  date: 2019-06-03
- !ruby/object:Order
  book: *17
  reader: *18
  date: 2019-06-03
- !ruby/object:Order
  book: *15
  reader: *16
  date: 2019-06-03
- !ruby/object:Order
  book: *19
  reader: *16
  date: 2019-06-03
- !ruby/object:Order
  book: *19
  reader: *20
  date: 2019-06-03
- !ruby/object:Order
  book: *21
  reader: *10
  date: 2019-06-03
- !ruby/object:Order
  book: *22
  reader: *23
  date: 2019-06-03
